
B(         CStartBuildingDesigner                                              )
B(         CAutosaveDisabled                                                   )
B(         CLandVisible                                                        )
B(         CObjectViewer                                                       )
B(         CShowFallbackElevators                                              )
B(         CGraphVisible                                                       )
B(         CRenderSky                                                          )
B(         CRenderWeather                                                      )
B(         CRenderNight                                                        )
B(         CRenderSnow                                                         )
B(         CRenderMouseLine                                                    )
B(         CShowIssueIcons                                                     )
B(         CEnableCutTool                                                      )
B(         CEnableFPSCap                                                       )
B(         CDisableDefaultBuildingSet                                          )
B(         CDisableDefaultBuildingTextures                                     )
B(         CDisableDefaultTerrainConfig                                        )
B(         CDisableDefaultAchievements                                         )
B(         CDisableDefaultVehicleModels                                        )
B(         CDisableDefaultNewspaperArticles                                    )
B(         CDisableDefaultEvents                                               )
B(         CEnableSounds                                                       )
F(         CSongDelay                                                          )
B(         CUseOldTerrainRendering                                             )
B(         CShowLandTiling                                                     )
B(         CGammaCorrect                                                       )
F(         CEnvironmentSoundRate                                               )
F(         CDefaultLightTime                                                   )
I(         CMaxCorruptSaves                                                    )
B(         CLogUpdateTime                                                      )
B(         CInterpolateVehicles                                                )
B(         CBuildingTextureFiltering                                           )
B(         CLandTextureFiltering                                               )
B(         CHideUnderwater                                                     )
B(         CShowPollution                                                      )
I(         CCullingAlgo                                                        )
B(         CEnableDesignOrganizer                                              )
B(         CFastAdvanceTutorial                                                )
F(         CScrollSpeed                                                        )

I(         CPaletteFrames                                                      )
F(         CPaletteAnimationFramerate                                          )
F(         CTextAtlasWidth                                                     )
F(         CTextAtlasPadding                                                   )
F(         CTextResolution                                                     )
F(         CTextWidthAdjust                                                    )
F(         CXHeightAdjust                                                      )
F(         CZeroWidthAdjust                                                    )
  F(         CSatMapResolution
)

F(         CTileSize                                                           )
F(         CZTileSize                                                          )
F(         CDesignerGridSize                                                   )
F(         CMaxLandErrorClose                                                  )
F(         CMaxLandErrorFar                                                    )
F(         CLandSimpleDistance                                                 )
F(         CTreeSimpleDistance                                                 )
F(         CWaterSimpleDistance                                                )
F(         CLandErrorConcaveFactor                                             )
F(         CLandErrorColorFactor                                               )
F(         CMaxHeight                                                          )
F(         CDefaultLandSize                                                    )
F(         CCustomLandSize                                                     )
F(         CSuperflatHeight                                                    )
F(         CPreviewImageDistance                                               )
F(         CCityDistance                                                       )
F(         CCityExtent                                                         )
F(         CCityGrowthRate                                                     )
F(         CCityGrowthMinDemand                                                )
B(         CLogBusinessGrowthData                                              )
  F(CTargetUnemploymentBias0
) F(CTargetUnemploymentBias1M
) F(CRejobRate
)

  F(         CMinTreeSpacing
) F(         CTreeSpacingDeviation
) F(         CTreeInnerFrequency
) F(         CTreeOuterFrequency
) F(         CAquaticBuildingHeight
) I(         CTerrainChunking
) B(         CEnableCameraMovement
)

F(         CGameUpdateTime                                                     )
F(         CAutosaveInterval                                                   )
F(         CMaxAutosaveInterval                                                )
F(         CMapRenderInterval                                                  )
F(         CMaxPendingGameUpdate                                               )
F(         CStartYear                                                          )

F(         CLaneWidth                                                          )
F(         CRailGauge                                                          )
F(         CSholderWidth                                                       )
I(         CMaxIntersectionLegs                                                )
B(         CLeftHandTraffic                                                    )
F(         CMaxBridgeLength                                                    )
F(         CMaxSuspensionBridgeLength                                          )
F(         CMinRoadLength                                                      )
F(         CMaxGrade                                                           )
F(         CMinEdgeAngle                                                       )
F(         CMinPillarAngle                                                     )
F(         CMinSuspensionPillarAngle                                           )
F(         CRoadRise                                                           )
F(         CMinLaneSpace                                                       )
F(         CSidewalkRise                                                       )
F(         CSidewalkWidth                                                      )
F(         CSidewalkBezel                                                      )
F(         CSidewalkDown                                                       )
F(         CSidewalkDensity                                                    )
F(         CPavedRailDensity                                                   )
F(         CExpwyWallHeight                                                    )
F(         CExpwyWallWidth                                                     )
B(         CEnableEdgePlacement                                                )

B(         CEnableUTurn                                                        )
F(         CSnapDistance                                                       )
F(         CMinNodeDistance                                                    )
F(         CBulldozerSnapDistance                                              )
F(         CMinNodeDist                                                        )
F(         CBuildDistance                                                      )
F(         CMsToMph                                                            )
F(         CMsToKmph                                                           )
F(         CHeatMapTime                                                        )
F(         CCameraLag                                                          )
F(         CDensePavementZ                                                     )
F(         CPavementDensity                                                    )
F(         CTrafficRate0                                                       )
F(         CTrafficRate100K                                                    )
F(         CTrafficRate1M                                                      )
F(         CMaxVehicles                                                        )
F(         CMaxVehicleAge                                                      )
F(         CAStarFactor                                                        )
F(         CHeadlightSizeY                                                     )
F(         CHeadlightSizeZ                                                     )
F(         CHeadlightCullDistance                                              )
F(         CRoutingTrafficAwareness                                            )
F(         CTraversalRecordMax                                                 )
F(         CTraversalRecordDynamism                                            )
F(         CStopLightMinPhaseDuration                                          )
F(         CStopLightMaxPhaseDuration                                          )
F(         CStopLightYellowDuration                                            )
F(         CStopSignDuration                                                   )

F(         CRouterCacheDiscardRate                                             )
F(         CRouterCacheCapacity                                                )
F(         CRouterStopDiscardingThreshold                                      )
F(         CRouterQueueCapacity                                                )
F(         CRouterBatchSize                                                    )
I(         CNumRouterThreads                                                   )
I(         CRouterSlowGameThreshold1                                           )
I(         CRouterSlowGameThreshold2                                           )
I(         CRouterSlowGameThreshold3                                           )
I(         CHeapOutdegree                                                      )
I(         CGameSpeedSmoothing                                                 )
I(         CSupplyTableUpdateRate                                              )
I(         CBrokerSearchDistance                                               )

F(         CVehicleSpeed                                                       )
F(         CVehicleAcceleration                                                )
F(         CVehicleUpdateTime                                                  )
F(         CMaxCommute                                                         )
F(         CTripLimitMultiplier                                                )
F(         CMaxSpawn                                                           )
F(         CBumperDistance                                                     )
F(         CMergeDistance                                                      )
F(         CMergeSpace                                                         )
F(         CMergeMaxSpeedDiff                                                  )
F(         CVehicleLengthForCapacity                                           )
F(         CBackpressureFactor                                                 )
F(         CBackpressureBias                                                   )
F(         CTruckDensity                                                       )
F(         CTruckWear                                                          )
F(         CTruckValue                                                         )
F(         CTruckPollution                                                     )
F(         CTruckProsperity                                                    )
F(         CVehicleDensity                                                     )
F(         CVehicleWear                                                        )
F(         CVehicleValue                                                       )
F(         CVehiclePollution                                                   )
F(         CVehicleProsperity                                                  )
F(         CTransitDensity                                                     )
F(         CWearRate                                                           )
F(         CRepairCost                                                         )
F(         CVehicleHeatmapTime                                                 )
F(         CEnableSemis                                                        )

F(         CNationalHSEdu                                                      )
F(         CNationalBclEdu                                                     )
F(         CNationalPhdEdu                                                     )
F(         CEducationMix                                                       )
F(         CEducationNationalMix                                               )

B(         CEnableTaxLock                                                      )
B(         CEnableBusinessClosing                                              )
F(         CNoCustomersStress                                                  )
F(         CNoFreightStress                                                    )
F(         CUnfilledPositionStress                                             )
F(         CBusinessSpawnRate                                                  )
F(         CFamilySpawnRate                                                    )
F(         CUnemploymentHomelessness                                           )
F(         CCommunityHomelessness                                              )
F(         CResDemandHomelessness                                              )
F(         CHomelessHealth                                                     )
F(         CBusinessProsperityStress                                           )
F(         CBusinessStressBase                                                 )
F(         CBusinessUnemploymentStress                                         )
F(         CBusinessStressThreshold                                            )
F(         CBusinessOpenHour                                                   )
F(         CBusinessCloseHour                                                  )
F(         COnTheJobTarget                                                     )
F(         CFreightOutDays                                                     )
F(         CFreightInDays                                                      )
F(         CCustomerDays                                                       )
F(         CFreightInIssue                                                     )
F(         CFreightOutIssue                                                    )
F(         CCustomerIssue                                                      )
F(         CUnfilledJobsIssue                                                  )

I(         CRetailNoEduPositions                                               )
I(         CRetailHSPositions                                                  )
I(         CRetailBclPositions                                                 )
I(         CRetailPhdPositions                                                 )

I(         COfficeNoEduPositions                                               )
I(         COfficeHSPositions                                                  )
I(         COfficeBclPositions                                                 )
I(         COfficePhdPositions                                                 )

I(         CFarmNoEduPositions                                                 )
I(         CFarmHSPositions                                                    )
I(         CFarmBclPositions                                                   )
I(         CFarmPhdPositions                                                   )

I(         CFactoryNoEduPositions                                              )
I(         CFactoryHSPositions                                                 )
I(         CFactoryBclPositions                                                )
I(         CFactoryPhdPositions                                                )

I(         CParkNoEduPositions                                                 )
I(         CParkHSPositions                                                    )
I(         CParkBclPositions                                                   )
I(         CParkPhdPositions                                                   )

I(         CEducationNoEduPositions                                            )
I(         CEducationHSPositions                                               )
I(         CEducationBclPositions                                              )
I(         CEducationPhdPositions                                              )

I(         CServicesNoEduPositions                                             )
I(         CServicesHSPositions                                                )
I(         CServicesBclPositions                                               )
I(         CServicesPhdPositions                                               )

F(         CPollutionInit                                                      )
F(         CPollutionEffect                                                    )
F(         CPollutionDissipationRate                                           )
F(         CPollutionCoastEffect                                               )
F(         CPollutionCoastEnd                                                  )
F(         CPollutionHillEffect                                                )
F(         CPollutionHillStart                                                 )
F(         CPollutionHillEnd                                                   )

F(         CValueInit                                                          )
F(         CValueEffect                                                        )
F(         CValueDissipationRate                                               )

F(         CValueCapBase                                                       )
F(         CValueCapEducation                                                  )
F(         CValueCapProsperity                                                 )
F(         CValueCapCrime                                                      )
F(         CValueCapPollution                                                  )
F(         CValueCapDensity                                                    )
F(         CValueCapCommunity                                                  )
F(         CValueCapHealth                                                     )
F(         CCrimeInfluenceOnValue                                              )
F(         CPollutionInfluenceOnValue                                          )
F(         CEducationInfluenceOnValue                                          )
F(         CDensityInfluenceOnValue                                            )

F(         CValueCoastTarget                                                   )
F(         CValueCoastEnd                                                      )
F(         CValueHillTarget                                                    )
F(         CValueHillStart                                                     )
F(         CValueHillEnd                                                       )
F(         CValueSuperflat                                                     )
  F(       CValueTerrainEffect
) F(       CNiceBuildingValue
) F(       CBadBuildingValue
) F(       CAbandonedBuildingValue
)

F(         CParkBeachPollution                                                 )
F(         CParkHillPollution                                                 )
F(         CParkLotPollution                                                 )
F(         CParkBeachValue                                                     )
F(         CParkHillValue                                                     )
F(         CParkLotValue                                                     )
F(         CParkLotMaint                                                     )
F(         CParkLotThrow                                                     )

F(         CDensityInit                                                        )
F(         CDensityEffect                                                      )
F(         CDensityDissipationRate                                             )
F(         CDensityInertia                                                     )
F(         CPopForMaxDensity                                                   )
F(         CDensityCapBase                                                     )
F(         CDensityCapProsperity                                               )
F(         CDensityCapEducation                                                )
F(         CDensityCapCrime                                                    )
F(         CDensityCapPollution                                                )
F(         CDensityCapCommunity                                                )
F(         CDensityCapHealth                                                   )

F(         CDensityCapCoastEffect                                              )
F(         CDensityCapCoastEnd                                                 )
F(         CDensityCapHillEffect                                               )
F(         CDensityCapHillStart                                                )
F(         CDensityCapHillEnd                                                  )

F(         CCrimeInit                                                          )
F(         CCrimeEffect                                                        )
F(         CCrimeDissipationRate                                               )
F(         CDensityCrime                                                       )
F(         CFinesAndFeesCrime                                                  )
F(         CAbandonedCrime                                                     )

F(         CEducationInit                                                      )
F(         CEducationEffect                                                    )
F(         CEducationDissipationRate                                           )

F(         CProsperityInit                                                     )
F(         CProsperityEffect                                                   )
F(         CProsperityDissipationRate                                          )

F(         CCommunityInit                                                      )
F(         CCommunityEffect                                                    )
F(         CCommunityDissipationRate                                           )
F(         CCommunityThrow                                                     )

F(         CCommunityCoastTarget                                               )
F(         CCommunityCoastEnd                                                  )

  F(       CCommunityParkEffect
) F(       CCommunityResidentialDens0Effect
) F(       CCommunityResidentialDens10Effect
) F(       CCommunityMixedUseBuildingEffect
) F(       CCommunityRetailBuildingEffect
) F(       CCommunityRetailBusinessEffect
) F(       CCommunityOfficeBuildingEffect
) F(       CCommunityFarmBuildingEffect
) F(       CCommunityFactoryBuildingEffect
) F(       CCommunitySickEffect
) F(       CCommunityProsperityInfluence
) F(       CAbandonedCommunity
) F(       CJoblessCommunity
) F(       CCommunityDensityInfluence
) F(       CCommunityAmenityEffect
) F(       CSickProsperity
) F(       CHungryHealth
)

F(         CHealthInit                                                         )
F(         CHealthEffect                                                       )
F(         CHealthDissipationRate                                              )
F(         CHealthParkEffect                                                   )
F(         CHealthPollutionInfluence                                           )
F(         CHealthCommunityInfluence
) F(       CPersonHealth
) F(       CHealthCrimeInfluence
) F(       CHealthThrow
) F(       CHealthVehicleEffect
) F(       CHealthTruckEffect
) F(       CAmenityHealthEffect
) F(       CSickHealthEffect
) F(       CJoblessHealth
) F(       CTouristsPerPoint
) F(       CTouristStay0
) F(       CTouristStay5
) F(       CTouristProsperity
) F(       CTouristCrime0
) F(       CTouristCrime5
) F(       CAmenityBaseScoreTourist
) F(       CStoreBaseScoreTourist

) F(       CMemoriesForFiveStars
) F(       CMemoriesPerTourismPoint
) F(       CHungryTouristMemories
) F(       CSickTouristMemories
) F(       CNoHotelMemories
) F(       CTransitMemories
) F(       CPrestigeMemories
) F(       CTouristMemoriesPollution
) F(       CTouristMemoriesValue
) F(       CTouristMemoriesDensity
) F(       CTouristMemoriesCrime
) F(       CTouristMemoriesProsperity
) F(       CTouristMemoriesCommunity
) F(       CTouristMemoriesHeath
) F(       CHotelRoomBuildingValue
)


F(         CMoveInProsperity                                                   )
F(         CHungryFamilyCrime                                                  )
F(         CHungryFamilyProsperity                                             )
F(         CHomelessProsperity                                                 )
F(         CJoblessProsperity                                                  )
F(         CJoblessFamilyProsperity                                            )
F(         CJoblessCrime                                                       )
F(         CJoblessFamilyCrime                                                 )
B(         CEnableMoveOuts                                                     )

B(         CAllowUniversityAtStart                                             )
F(         CAmenityStudentScore                                                )
F(         CPhdEducationEffect                                                 )
F(         CPhdEducationProsperity                                             )
F(         CPhdEducationCrime                                                  )
F(         CBclEducationEffect                                                 )
F(         CBclEducationProsperity                                             )
F(         CBclEducationCrime                                                  )
F(         CHSEducationEffect                                                  )
F(         CHSEducationProsperity                                              )
F(         CHSEducationCrime                                                   )
F(         CNoEducationEffect                                                  )
F(         CNoEducationProsperity                                              )
F(         CNoEducationCrime                                                   )

F(         CRouteFailedProsperity                                              )
F(         CSuccessfulTripProsperity                                           )
F(         CLongTripProsperity                                                 )
F(         CShoppingTripDensity                                                )
F(         CShoppingTripProsperity                                             )
F(         CFreightDeliveryPropserity                                          )

F(         CEmptyLotDensity                                                    )
F(         CEmptyTenancyDensity                                                )
F(         CAbandonedDensity                                                   )
F(         COfficeDensity                                                      )
F(         CFactoryDensity                                                     )
F(         CBusinessProsperity                                                 )
F(         CUnfilledPositionProsperity                                         )
F(         CNoFreightProsperity                                                )
F(         CNoCustomerProsperity                                               )
F(         CEmployedProsperity
 )

F(         CRoadBuiltProsperity                                                )
F(         CLotZonedProsperity                                                 )
F(         CNewBuildingProsperity                                              )
F(         CNewAmenityProsperity                                               )
F(         CFamilyPollution                                                    )
F(         CStudentPollution                                                   )
F(         CFarmPollution                                                      )
F(         CFactoryPollution                                                   )
F(         CCommercialPollution                                                )
F(         CAbandonedProsperity                                                )

F(         CAmenityProsperityBonus                                             )
F(         CAmenityProsperityEffect                                            )
F(         CAmenityDensityBonus                                                )
F(         CAmenityDensityEffect                                               )
F(         CAmenityPollutionEffect                                             )
F(         CAmenityValueEffect                                                 )
F(         CAmenityCrimeEffect                                                 )
F(         CAmenityCommunityEffect                                             )

F(         CBuildingAddRate                                                    )
F(         CBuildingAddRateBase                                                )
F(         CBuildingUpgradeRate                                                )
F(         CBuildingUpdateTime                                                 )
F(         CBuildingUpdateSpread                                               )
F(         CSkyscraperMinHeight                                                )
I(         CSkyscraperMinDensity                                               )
F(         CBuildingNameworthyValue                                            )
F(         CBuildingCullMin                                                    )
F(         CBuildingCullSizeFactor                                             )
F(         CBuildingCullSimplify                                               )
F(         CBuildingCullDeco                                                   )
F(         CBuildingCullSimplifyDeco                                           )
F(         CBuildingCullZFactor                                                )
F(         CVehicleCull                                                        )
F(         CTransitVehicleCull                                                 )
F(         CWandererCull                                                       )
F(         CVehicleCullSimplify                                                )
F(         CLandCull                                                           )
F(         CTreeCull                                                           )
F(         CPersonEvaluateTime                                                 )
F(         CPersonUpdateTime                                                   )
F(         CPersonContributorNameChance                                        )
F(         CRoadContributorNameChance                                          )
F(         CMoveEconRate                                                       )
F(         CMaxAgeBase                                                         )
F(         CMaxAgeHealthAdjust                                                 )
F(         CDeathFactor                                                        )
F(         CRetirementAge                                                      )

F(         CRecommendedAmenityCost                                             )
F(         CRecommendedAmenityMaint                                            )
F(         CAmenityCostMult                                                    )
F(         CAmenityMaintMult                                                   )
F(         CAmenityPollutionThrow                                              )
F(         CAmenityValueThrow                                                  )
F(         CAmenityCrimeThrow                                                  )
F(         CAmenityEduThrow                                                    )
F(         CMaxHSEdu                                                           )
F(         CMaxBclEdu                                                          )
F(         CMaxPhdEdu                                                          )
F(         CEduFreq                                                            )
F(         CCommunityFreq                                                      )
F(         CMaxHSEduPerEffect                                                  )
F(         CMaxBclEduPerEffect                                                 )
F(         CMaxPhdEduPerEffect                                                 )
F(         CMaxHSEduPerCollege                                                 )
F(         CMaxBclEduPerCollege                                                )
F(         CMaxPhdEduPerCollege                                                )
F(         CUniversityMaxQuadDistance                                          )

I(         CMaxEffect                                                          )
F(         CTechEduBasis                                                       )
F(         CBusinessUnempBasis                                                 )
F(         CMaxResidentialDensity                                              )
F(         CPrestigeMaxResDensity                                              )
F(         CEnvironmentalismPollutionBasis                                     )
F(         COrderLawBasis                                                      )
F(         CCommunityCrimeBasis                                               )

F(         CMinActScore                                                        )
F(         CSleepBaseScore                                                     )
F(         CSleepSick                                                          )
F(         CSleepDayProxA                                                      )
F(         CSleepDayProxB                                                      )
F(         CSleepDayProxC                                                      )
F(         CSleepLightFactor                                                   )
F(         CSleepInertiaA                                                      )
F(         CSleepInertiaB                                                      )
F(         CSleepInertiaC                                                      )

F(         CHomeBaseScore                                                      )
F(         CHomeSick                                                           )
F(         CHomeDayProxA                                                       )
F(         CHomeDayProxB                                                       )
F(         CHomeDayProxC                                                       )
F(         CHomeLightFactor                                                    )
F(         CHomeInertiaA                                                       )
F(         CHomeInertiaB                                                       )
F(         CHomeInertiaC                                                       )
F(         CHomeUnemployed                                                     )

F(         CFriendBaseScore                                                    )
F(         CFriendSick                                                         )
F(         CFriendDayProxA                                                     )
F(         CFriendDayProxB                                                     )
F(         CFriendDayProxC                                                     )
F(         CFriendLightFactor                                                  )
F(         CFriendInertiaA                                                     )
F(         CFriendInertiaB                                                     )
F(         CFriendInertiaC                                                     )
F(         CFriendEnergy                                                       )
F(         CFriendHomeless                                                     )

F(         CWorkBaseScore                                                      )
F(         CWorkSick                                                           )
F(         CWorkDayProxA                                                       )
F(         CWorkDayProxB                                                       )
F(         CWorkDayProxC                                                       )
F(         CWorkLightFactor                                                    )
F(         CWorkInertiaA                                                       )
F(         CWorkInertiaB                                                       )
F(         CWorkInertiaC                                                       )
F(         CWorkOpenFactor                                                     )
F(         CWorkTimeSince                                                      )

F(         CInterviewBaseScore                                                 )
F(         CInterviewSick                                                      )
F(         CInterviewDayProxA                                                  )
F(         CInterviewDayProxB                                                  )
F(         CInterviewDayProxC                                                  )
F(         CInterviewLightFactor                                               )
F(         CInterviewInertiaA                                                  )
F(         CInterviewInertiaB                                                  )
F(         CInterviewInertiaC                                                  )
F(         CInterviewTimeSince                                                 )
F(         CInterviewEducation                                                 )

F(         CStoreBaseScore                                                     )
F(         CStoreSick                                                          )
F(         CStoreDayProxA                                                      )
F(         CStoreDayProxB                                                      )
F(         CStoreDayProxC                                                      )
F(         CStoreLightFactor                                                   )
F(         CStoreProsperityFactor                                              )
F(         CStoreInertiaA                                                      )
F(         CStoreInertiaB                                                      )
F(         CStoreInertiaC                                                      )
F(         CStoreTimeSince                                                     )

F(         CFreightBaseScore                                                   )
F(         CFreightSick                                                        )
F(         CFreightA                                                           )
F(         CFreightB                                                           )
F(         CFreightC                                                           )
F(         CFreightDayProxA                                                    )
F(         CFreightDayProxB                                                    )
F(         CFreightDayProxC                                                    )

F(         CAmenityBaseScore                                                   )
F(         CAmenityOpenPerPop                                                  )
F(         CAmenityOpenMax                                                     )
F(         CAmenityDayProxA                                                    )
F(         CAmenityDayProxB                                                    )
F(         CAmenityDayProxC                                                    )
F(         CAmenityHomeless                                                    )
F(         CParkTime                                                           )
F(         CEducationTime                                                      )
F(         CUniversityTime                                                     )
F(         CServicesTime                                                       )
F(         CAmenityInertiaA                                                    )
F(         CAmenityInertiaB                                                    )
F(         CAmenityCapacity                                                    )

F(         CDoctorBaseScore                                                   )
F(         CDoctorDayProxA                                                    )
F(         CDoctorDayProxB                                                    )
F(         CDoctorDayProxC                                                    )
F(         CDoctorSick                                                        )
F(         CDoctorInertiaA                                                    )
F(         CDoctorInertiaB                                                    )
F(         CDoctorInertiaC                                                    )

F(         CSickTransferRate                                                  )
F(         CSickRateMinHealth                                                 )
F(         CSickRateMaxHealth                                                 )
F(         CSickHealRate                                                      )

F(         CCollegeEduRetailSpending                                           )
F(         CHSEduRetailSpending                                                )
F(         CNoEduRetailSpending                                                )
F(         CGoodFaithLOC                                                       )
F(         CStartingMoney                                                      )
F(         CMoneyMultiplier                                                    )
F(         CPropertyTaxUnemploymentEffect                                      )
F(         CPropertyTaxResidentialEffect                                       )
F(         CSalesTaxUnemploymentEffect                                         )
F(         CSalesTaxRetailEffect                                               )
F(         CFinesAndFeesTaxUnemploymentEffect                                  )

F(         CEminentDomainFactor                                                )
F(         CBuildingSalesFactor                                                )
F(         CLandValue                                                          )
F(         CLandValueMultiplier                                                )
F(         CDensityMultiplier                                                  )
F(         CDensityMultiplierIndustrial                                        )
F(         CBuildingValue                                                      )
F(         CBusinessBuildingValue                                              )
F(         CHomeBuildingValue                                                  )
F(         CAquaticBuildingValue                                               )
F(         CMaxDesignCommonness                                                )

F(         CAssetLOC                                                           )
F(         CMaxBudgetControl                                                   )
F(         CBudgetControlFactor                                                )
F(         CFinesPerPerson                                                     )
F(         CFinesPerBusiness                                                   )

F(         CEmbankmentCost                                                     )
F(         CTrenchCost                                                         )
F(         CViaductCost                                                        )
F(         CTunnelCost                                                         )
F(         CLaneCostRoad                                                       )
F(         CLaneCostExpwy                                                      )
F(         CLaneCostRail                                                       )
F(         CPlatformCost                                                       )
F(         CWalkwayCost                                                        )
F(         CMinReconfigureCostRoad                                             )
F(         CMinReconfigureCostExpwy                                            )
F(         CMinReconfigureCostRail                                             )
F(         CStrategyCostStopSign                                               )
F(         CStrategyCostTrafficLight                                           )
F(         CStrategyCostJunction                                               )
F(         CPillarCost                                                         )
F(         CPillarCostSuspension                                               )
F(         CPillarCostExponent                                                 )
F(         CDestroyRoadCost                                                    )
F(         CDestroyPillarCost                                                  )
F(         CPillarHeight                                                       )
F(         CTreesAddCost                                                       )
F(         CTreesAddRate                                                       )
F(         CEarthworksCost                                                     )

F(         CStopCost                                                           )
F(         CStopRadius                                                         )
F(         CWalkingSpeed                                                       )
F(         CTransitLineWidth                                                   )
F(         CDefaultTransitHeadway                                              )
F(         CDefaultTicketPrice                                                 )
F(         CDefaultTransferPrice                                               )
F(         CNewTrackTicketPrice                                                )
F(         CNewTrackTransferPrice                                              )
F(         CLitersPerMinuteBus                                                 )
F(         CLitersPerMinuteCar                                                 )
F(         CMaintPerMinuteBus                                                  )
F(         CMaintPerMinuteCar                                                  )
F(         CValueOfTime                                                        )
F(         CTransitBias                                                        )
I(         CNumTransitBids                                                     )
F(         CTransitDesignTime                                                  )
F(         CTransitDesignDelayChance                                           )
F(         CMaxCarsPerVehicle                                                  )
F(         CAlightingRate                                                      )

F(         CMaxUnemploymentDiff                                                )
F(         CStoreDays                                                          )
F(         CWorkDays                                                           )
F(         CStoreIssueDays                                                     )
F(         CWorkIssueDays                                                      )

F(         CTargetEmptyHomes                                                   )
F(         CTargetEmptyCommercial                                              )
F(         CTargetEmptyIndustrial                                              )
F(         CRetailEconomyPerBiz                                                )
F(         CBizPerBizPoint                                                     )
F(         CMaxOpenJobs                                                        )
F(         CUnderemploymentRate                                                )

F(         CBusinessUnemploymentFactor                                         )
F(         CUnemploymentRetailBias                                             )
F(         CUnemploymentOfficeBias                                             )
F(         CUnemploymentFarmBias                                               )
F(         CUnemploymentFactoryBias                                            )

F(         CMinCameraDistance                                                  )
F(         CMaxPitch                                                           )
F(         CMinPitch                                                           )
F(         CPitchClassic                                                       )
F(         CCameraFOV                                                          )
F(         CCameraSpringSpeed                                                  )
F(         CCameraPitchSpeed                                                   )
F(         CCameraYawSpeed                                                     )
F(         CCameraYawKeySpeed                                                  )
F(         CCameraSpeedX                                                       )
F(         CCameraSpeedY                                                       )
F(         CCameraZoomSpeed                                                    )
F(         CCameraKeyZoomSpeed                                                 )
F(         CCameraPanSpeed                                                     )
F(         CCameraPanSpeedClassic                                              )
F(         CCameraPanSmoothing                                                 )
F(         CMeshQuality                                                        )
F(         CLotVisibleDistance                                                 )

F(         CSnowCollectionRate                                                 )
B(         CEnableNewspaper                                                    )
B(         CLogNewspaperData                                                   )
F(         CNewspaperPrice                                                     )
F(         CNewspaperRandomness                                                )
I(         CNumNewspaperArticles                                               )
I(         CNewspaperMinLength                                                 )
B(         CNewspaperTextured                                                  )
I(         CNumNewspaperSportsScores                                           )
B(         CHourlyNewspaper                                                    )
